export interface FuturoQuestionItem {
  id: number; // 51 to 70
  index: number; // 0 to 19
  spanishSentence: string;
  blankWord: string;
  armenianTranslation: string;
  tenseName: string;
  options: {
    key: 'A' | 'B' | 'C' | 'D';
    text: string;
  }[];
  correctAnswer: 'A' | 'B' | 'C' | 'D';
  explanation: string;
  // Corresponding tongue twister (скороговорка) unlocked on correct answer
  trabalengua: {
    id: number;
    spanish: string;
    armenian: string;
  };
}

export const FUTURO_QUESTIONS: FuturoQuestionItem[] = [
  {
    id: 51,
    index: 0,
    spanishSentence: 'Mañana yo ______ temprano.',
    blankWord: 'me levantaré',
    armenianTranslation: 'Վաղը ես շուտ կարթնանամ։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'me levantaré' },
      { key: 'B', text: 'me levanté' },
      { key: 'C', text: 'me levanto' },
      { key: 'D', text: 'me levantaba' },
    ],
    correctAnswer: 'A',
    explanation: '«Mañana» (վաղը) պահանջում է Futuro Simple (կանոնավոր բայ՝ levantar -> me levantaré)։',
    trabalengua: {
      id: 1,
      spanish: 'Paco pasa poco a poco por el parque con Pablo.',
      armenian: 'Պակոն կամաց-կամաց անցնում է այգով Պաբլոյի հետ։',
    },
  },
  {
    id: 52,
    index: 1,
    spanishSentence: 'El próximo verano nosotros ______ a España.',
    blankWord: 'viajaremos',
    armenianTranslation: 'Հաջորդ ամռանը մենք կճանապարհորդենք Իսպանիա։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'viajamos' },
      { key: 'B', text: 'viajaremos' },
      { key: 'C', text: 'hemos viajado' },
      { key: 'D', text: 'viajábamos' },
    ],
    correctAnswer: 'B',
    explanation: '«El próximo verano» (հաջորդ ամռանը) ապառնի գործողություն է՝ viajar -> viajaremos։',
    trabalengua: {
      id: 2,
      spanish: 'Manuel manda mensajes mientras mira montañas.',
      armenian: 'Մանուելը հաղորդագրություններ է ուղարկում, մինչ նայում է լեռներին։',
    },
  },
  {
    id: 53,
    index: 2,
    spanishSentence: 'Tú ______ mucho español este año.',
    blankWord: 'aprenderás',
    armenianTranslation: 'Այս տարի դու շատ իսպաներեն կսովորես։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'aprenderás' },
      { key: 'B', text: 'aprendiste' },
      { key: 'C', text: 'aprendes' },
      { key: 'D', text: 'has aprendido' },
    ],
    correctAnswer: 'A',
    explanation: 'Խոստում կամ ապագայի ծրագիր tú դերանվան համար՝ aprender -> aprenderás։',
    trabalengua: {
      id: 3,
      spanish: 'Rosa riega rosas rojas alrededor de su casa.',
      armenian: 'Ռոսան իր տան շուրջը ջրում է կարմիր վարդերը։',
    },
  },
  {
    id: 54,
    index: 3,
    spanishSentence: 'Carlos ______ mañana con sus amigos.',
    blankWord: 'quedará',
    armenianTranslation: 'Կառլոսը վաղը կհանդիպի իր ընկերների հետ։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'queda' },
      { key: 'B', text: 'quedará' },
      { key: 'C', text: 'quedó' },
      { key: 'D', text: 'ha quedado' },
    ],
    correctAnswer: 'B',
    explanation: '«Mañana» (վաղը) Carlos (él) դեմքի համար՝ quedar -> quedará։',
    trabalengua: {
      id: 4,
      spanish: 'Carlos corta cinco cocos con cuidado.',
      armenian: 'Կառլոսը զգուշությամբ կտրում է հինգ կոկոս։',
    },
  },
  {
    id: 55,
    index: 4,
    spanishSentence: 'Esta noche nosotros ______ una película.',
    blankWord: 'veremos',
    armenianTranslation: 'Այսօր երեկոյան մենք ֆիլմ կդիտենք։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'vimos' },
      { key: 'B', text: 'veremos' },
      { key: 'C', text: 'vemos' },
      { key: 'D', text: 'hemos visto' },
    ],
    correctAnswer: 'B',
    explanation: '«Esta noche» (այսօր երեկոյան, ապագայում) nosotros համար՝ ver -> veremos։',
    trabalengua: {
      id: 5,
      spanish: 'Marta mezcla miel, mango y manzana por la mañana.',
      armenian: 'Մարտան առավոտյան խառնում է մեղր, մանգո և խնձոր։',
    },
  },
  {
    id: 56,
    index: 5,
    spanishSentence: 'El sábado ellos ______ al fútbol.',
    blankWord: 'jugarán',
    armenianTranslation: 'Շաբաթ օրը նրանք ֆուտբոլ կխաղան։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'juegan' },
      { key: 'B', text: 'jugarán' },
      { key: 'C', text: 'jugaron' },
      { key: 'D', text: 'han jugado' },
    ],
    correctAnswer: 'B',
    explanation: '«El sábado» գալիք շաբաթ օրվա համար ellos ձևն է՝ jugar -> jugarán։',
    trabalengua: {
      id: 6,
      spanish: 'Pedro prepara pan para Pablo y Paula.',
      armenian: 'Պեդրոն Պաբլոյի և Պաուլայի համար հաց է պատրաստում։',
    },
  },
  {
    id: 57,
    index: 6,
    spanishSentence: 'Yo te ______ después de clase.',
    blankWord: 'llamaré',
    armenianTranslation: 'Դասից հետո ես քեզ կզանգեմ։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'llamé' },
      { key: 'B', text: 'llamaré' },
      { key: 'C', text: 'llamo' },
      { key: 'D', text: 'he llamado' },
    ],
    correctAnswer: 'B',
    explanation: 'Խոստում yo դեմքով՝ llamar -> llamaré։',
    trabalengua: {
      id: 7,
      spanish: 'Lucía limpia lentamente las lámparas lilas.',
      armenian: 'Լուսիան դանդաղ մաքրում է մանուշակագույն լամպերը։',
    },
  },
  {
    id: 58,
    index: 7,
    spanishSentence: '¿Qué ______ mañana por la tarde?',
    blankWord: 'harás',
    armenianTranslation: 'Վաղը կեսօրից հետո ի՞նչ կանես։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'hiciste' },
      { key: 'B', text: 'harás' },
      { key: 'C', text: 'haces' },
      { key: 'D', text: 'has hecho' },
    ],
    correctAnswer: 'B',
    explanation: '«Hacer» բայի Futuro Simple անկանոն հիմքն է har-՝ tú harás։',
    trabalengua: {
      id: 8,
      spanish: 'Sofía sonríe siempre si sale el sol.',
      armenian: 'Սոֆիան միշտ ժպտում է, եթե արև է դուրս գալիս։',
    },
  },
  {
    id: 59,
    index: 8,
    spanishSentence: 'Mi hermano ______ la guitarra esta noche.',
    blankWord: 'tocará',
    armenianTranslation: 'Իմ եղբայրն այսօր երեկոյան կիթառ կնվագի։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'tocará' },
      { key: 'B', text: 'toca' },
      { key: 'C', text: 'tocó' },
      { key: 'D', text: 'ha tocado' },
    ],
    correctAnswer: 'A',
    explanation: '«Mi hermano» (él) համար ապառնի ժամանակով՝ tocar -> tocará։',
    trabalengua: {
      id: 9,
      spanish: 'Bruno bebe batido de banana bajo un árbol.',
      armenian: 'Բրունոն ծառի տակ բանանի կոկտեյլ է խմում։',
    },
  },
  {
    id: 60,
    index: 9,
    spanishSentence: 'Nosotros ______ después del trabajo.',
    blankWord: 'descansaremos',
    armenianTranslation: 'Մենք աշխատանքից հետո կհանգստանանք։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'descansamos' },
      { key: 'B', text: 'descansaremos' },
      { key: 'C', text: 'descansamos ayer' },
      { key: 'D', text: 'hemos descansado' },
    ],
    correctAnswer: 'B',
    explanation: 'Ապագա գործողություն nosotros դեմքով՝ descansar -> descansaremos։',
    trabalengua: {
      id: 10,
      spanish: 'Tomás toca tres tambores todos los martes.',
      armenian: 'Տոմասը ամեն երեքշաբթի երեք թմբուկ է նվագում։',
    },
  },
  {
    id: 61,
    index: 10,
    spanishSentence: 'Tú ______ la verdad mañana.',
    blankWord: 'sabrás',
    armenianTranslation: 'Դու վաղը կիմանաս ճշմարտությունը։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'sabrás' },
      { key: 'B', text: 'sabes' },
      { key: 'C', text: 'supiste' },
      { key: 'D', text: 'has sabido' },
    ],
    correctAnswer: 'A',
    explanation: '«Saber» բայի ապառնի անկանոն հիմքն է sabr- -> tú sabrás։',
    trabalengua: {
      id: 11,
      spanish: 'Clara compra cuatro cuadernos con cuadros.',
      armenian: 'Կլարան գնում է չորս վանդակավոր տետր։',
    },
  },
  {
    id: 62,
    index: 11,
    spanishSentence: 'Pablo ______ más tiempo la próxima semana.',
    blankWord: 'tendrá',
    armenianTranslation: 'Պաբլոն հաջորդ շաբաթ ավելի շատ ժամանակ կունենա։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'tiene' },
      { key: 'B', text: 'tendrá' },
      { key: 'C', text: 'tuvo' },
      { key: 'D', text: 'ha tenido' },
    ],
    correctAnswer: 'B',
    explanation: '«Tener» բայի ապառնի անկանոն հիմքն է tendr- -> él tendrá։',
    trabalengua: {
      id: 12,
      spanish: 'Diego dibuja diez delfines durante el día.',
      armenian: 'Դիեգոն օրվա ընթացքում նկարում է տասը դելֆին։',
    },
  },
  {
    id: 63,
    index: 12,
    spanishSentence: 'Yo ______ todo mañana.',
    blankWord: 'haré',
    armenianTranslation: 'Ես վաղը ամեն ինչ կանեմ։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'hago' },
      { key: 'B', text: 'haré' },
      { key: 'C', text: 'hice' },
      { key: 'D', text: 'he hecho' },
    ],
    correctAnswer: 'B',
    explanation: '«Hacer» բայի ապառնի անկանոն ձևը yo համար՝ yo haré։',
    trabalengua: {
      id: 13,
      spanish: 'Nina nada nueve minutos en una piscina nueva.',
      armenian: 'Նինան նոր լողավազանում ինը րոպե լողում է։',
    },
  },
  {
    id: 64,
    index: 13,
    spanishSentence: 'Ellos ______ más tarde.',
    blankWord: 'vendrán',
    armenianTranslation: 'Նրանք ավելի ուշ կգան։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'vienen' },
      { key: 'B', text: 'vendrán' },
      { key: 'C', text: 'vinieron' },
      { key: 'D', text: 'han venido' },
    ],
    correctAnswer: 'B',
    explanation: '«Venir» բայի ապառնի անկանոն հիմքն է vendr- -> ellos vendrán։',
    trabalengua: {
      id: 14,
      spanish: 'Felipe feliz fotografía flores frente a la fuente.',
      armenian: 'Ուրախ Ֆելիպեն շատրվանի մոտ ծաղիկներ է լուսանկարում։',
    },
  },
  {
    id: 65,
    index: 14,
    spanishSentence: 'Nosotros ______ ayudarte.',
    blankWord: 'podremos',
    armenianTranslation: 'Մենք կկարողանանք քեզ օգնել։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'podemos' },
      { key: 'B', text: 'podremos' },
      { key: 'C', text: 'pudimos' },
      { key: 'D', text: 'hemos podido' },
    ],
    correctAnswer: 'B',
    explanation: '«Poder» բայի ապառնի անկանոն հիմքն է podr- -> nosotros podremos։',
    trabalengua: {
      id: 15,
      spanish: 'Gabriel guarda galletas grandes para sus amigos.',
      armenian: 'Գաբրիելը մեծ թխվածքաբլիթներ է պահում իր ընկերների համար։',
    },
  },
  {
    id: 66,
    index: 15,
    spanishSentence: 'Tú ______ la mesa antes de cenar.',
    blankWord: 'pondrás',
    armenianTranslation: 'Դու ընթրիքից առաջ սեղանը կդնես։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'pondrás' },
      { key: 'B', text: 'pones' },
      { key: 'C', text: 'pusiste' },
      { key: 'D', text: 'has puesto' },
    ],
    correctAnswer: 'A',
    explanation: '«Poner» բայի ապառնի անկանոն հիմքն է pondr- -> tú pondrás։',
    trabalengua: {
      id: 16,
      spanish: 'Elena elige helados de fresa en el mercado.',
      armenian: 'Էլենան շուկայում ընտրում է ելակի պաղպաղակ։',
    },
  },
  {
    id: 67,
    index: 16,
    spanishSentence: 'Mañana él ______ de casa a las ocho.',
    blankWord: 'saldrá',
    armenianTranslation: 'Վաղը նա ժամը ութին տնից դուրս կգա։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'sale' },
      { key: 'B', text: 'saldrá' },
      { key: 'C', text: 'salió' },
      { key: 'D', text: 'ha salido' },
    ],
    correctAnswer: 'B',
    explanation: '«Salir» բայի ապառնի անկանոն հիմքն է saldr- -> él saldrá։',
    trabalengua: {
      id: 17,
      spanish: 'Víctor visita varios pueblos verdes en verano.',
      armenian: 'Վիկտորը ամռանը այցելում է մի քանի կանաչ գյուղեր։',
    },
  },
  {
    id: 68,
    index: 17,
    spanishSentence: 'Yo te ______ la respuesta mañana.',
    blankWord: 'diré',
    armenianTranslation: 'Ես վաղը քեզ պատասխանը կասեմ։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'diré' },
      { key: 'B', text: 'digo' },
      { key: 'C', text: 'dije' },
      { key: 'D', text: 'he dicho' },
    ],
    correctAnswer: 'A',
    explanation: '«Decir» բայի ապառնի անկանոն հիմքն է dir- -> yo diré։',
    trabalengua: {
      id: 18,
      spanish: 'Carmen cocina crema de calabaza con cariño.',
      armenian: 'Կարմենը սիրով դդմի կրեմ-ապուր է պատրաստում։',
    },
  },
  {
    id: 69,
    index: 18,
    spanishSentence: 'Este fin de semana nosotros ______ a nuestros abuelos.',
    blankWord: 'visitaremos',
    armenianTranslation: 'Այս հանգստյան օրերին մենք կայցելենք մեր տատիկին և պապիկին։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'visitamos' },
      { key: 'B', text: 'visitaremos' },
      { key: 'C', text: 'visitamos ayer' },
      { key: 'D', text: 'hemos visitado' },
    ],
    correctAnswer: 'B',
    explanation: '«Este fin de semana» (ապագայում) nosotros համար՝ visitar -> visitaremos։',
    trabalengua: {
      id: 19,
      spanish: 'Javier juega junto al jardín con Julia y José.',
      armenian: 'Խավիերը այգու մոտ խաղում է Խուլիայի և Խոսեի հետ։',
    },
  },
  {
    id: 70,
    index: 19,
    spanishSentence: 'El próximo mes ellos ______ una casa nueva.',
    blankWord: 'comprarán',
    armenianTranslation: 'Հաջորդ ամիս նրանք նոր տուն կգնեն։',
    tenseName: 'futuro simple',
    options: [
      { key: 'A', text: 'comprarán' },
      { key: 'B', text: 'compran' },
      { key: 'C', text: 'compraron' },
      { key: 'D', text: 'han comprado' },
    ],
    correctAnswer: 'A',
    explanation: '«El próximo mes» (հաջորդ ամիս) ellos համար՝ comprar -> comprarán։',
    trabalengua: {
      id: 20,
      spanish: 'Raúl recoge rosas, ramas y romero rápidamente.',
      armenian: 'Ռաուլը արագ հավաքում է վարդեր, ճյուղեր և խնկունի։',
    },
  },
];
